# Generated by Django 2.2.2 on 2019-11-16 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('familyManage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(db_column='用户ID', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='用户名', max_length=10)),
                ('password', models.CharField(db_column='密码', max_length=64)),
                ('telephone', models.CharField(blank=True, db_column='电话', max_length=11)),
                ('email', models.EmailField(blank=True, db_column='邮箱', max_length=40)),
                ('sex', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], db_column='性别', default=1)),
                ('family1', models.ForeignKey(blank=True, db_column='家庭1', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family1', to='familyManage.Family')),
                ('family2', models.ForeignKey(blank=True, db_column='家庭2', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family2', to='familyManage.Family')),
            ],
            options={
                'db_table': '用户表',
            },
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userManage.User')),
            ],
        ),
    ]
