# Generated by Django 2.2.2 on 2019-11-19 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userManage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='family2',
        ),
    ]
