# Generated by Django 2.2.2 on 2019-11-16 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userManage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='标题', max_length=24)),
                ('text', models.TextField(db_column='内容', max_length=1000)),
                ('send_time', models.DateTimeField(auto_now_add=True, db_column='发送时间')),
                ('state', models.SmallIntegerField(choices=[(0, '未读'), (1, '星标'), (2, '已读')], db_column='状态', default=0)),
                ('receive', models.ForeignKey(db_column='接收者', on_delete=django.db.models.deletion.CASCADE, related_name='receive', to='userManage.User')),
                ('send', models.ForeignKey(db_column='发送者', on_delete=django.db.models.deletion.CASCADE, related_name='send', to='userManage.User')),
            ],
            options={
                'db_table': 'MessageDT',
            },
        ),
    ]
