# Generated by Django 2.2.2 on 2019-11-24 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageManage', '0002_message_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='state',
            field=models.SmallIntegerField(choices=[(0, '未读'), (1, '星标'), (2, '已读'), (3, '非星标')], db_column='状态', default=0),
        ),
    ]
