# Generated by Django 2.2.2 on 2019-12-13 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('familyManage', '0001_initial'),
        ('userManage', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBills',
            fields=[
                ('id', models.BigAutoField(db_column='账单ID', primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now_add=True, db_column='创建时间')),
                ('money', models.FloatField(db_column='金额')),
                ('type', models.SmallIntegerField(choices=[(0, '收入'), (1, '借来的钱'), (10, '支出'), (11, '借出去的钱'), (12, '存入银行的钱')], db_column='类型')),
                ('remarks', models.TextField(blank=True, db_column='备注', max_length=1000)),
                ('user', models.ForeignKey(db_column='用户', on_delete=django.db.models.deletion.CASCADE, to='userManage.User')),
            ],
            options={
                'db_table': '账单',
            },
        ),
        migrations.CreateModel(
            name='FamilyBills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bills_id', models.ForeignKey(db_column='账单号', on_delete=django.db.models.deletion.CASCADE, to='billsManage.UserBills')),
                ('family_id', models.ForeignKey(db_column='家庭ID', on_delete=django.db.models.deletion.CASCADE, to='familyManage.Family')),
            ],
            options={
                'db_table': '家庭账单',
            },
        ),
    ]
