# Generated by Django 2.2.2 on 2019-12-13 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billsManage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userbills',
            table='用户账单',
        ),
    ]
