# Generated by Django 2.2.2 on 2019-12-14 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billsManage', '0002_auto_20191213_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbills',
            name='remarks',
            field=models.TextField(db_column='备注', max_length=1000),
        ),
    ]
