# Generated by Django 2.2.2 on 2019-12-14 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billsManage', '0004_auto_20191214_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbills',
            name='concrete_type',
            field=models.CharField(db_column='具体类型', default='其他', max_length=100),
        ),
    ]
