# Generated by Django 2.2.2 on 2019-12-19 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userManage', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowMoneyTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.IntegerField(db_column='金额')),
                ('date', models.DateField(auto_now_add=True, db_column='借款时间', null=True)),
                ('repayment_date', models.DateField(auto_now_add=True, db_column='发款时间')),
                ('borrower', models.ForeignKey(db_column='借款人', on_delete=django.db.models.deletion.CASCADE, related_name='borrower', to='userManage.User')),
                ('lender', models.ForeignKey(db_column='发借人', on_delete=django.db.models.deletion.CASCADE, related_name='lender', to='userManage.User')),
            ],
            options={
                'db_table': '借还钱管理表',
            },
        ),
    ]
