# Generated by Django 2.2.2 on 2019-12-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowingMoneyManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowmoneytable',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '未处理'), (1, '拒绝借款'), (2, '已发款'), (3, '已还款')], db_column='状态', default=0),
        ),
        migrations.AlterField(
            model_name='borrowmoneytable',
            name='repayment_date',
            field=models.DateField(auto_now_add=True, db_column='发款时间', null=True),
        ),
    ]
