# Generated by Django 2.2.2 on 2019-12-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowingMoneyManagement', '0002_auto_20191219_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowmoneytable',
            name='id',
            field=models.BigAutoField(db_column='ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='borrowmoneytable',
            name='repayment_date',
            field=models.DateField(auto_now_add=True, db_column='还款时间', null=True),
        ),
        migrations.AlterField(
            model_name='borrowmoneytable',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '未处理'), (1, '已发款'), (2, '已还款')], db_column='状态', default=0),
        ),
    ]
