# Generated by Django 2.2.2 on 2019-11-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(db_column='家庭ID', primary_key=True, serialize=False)),
                ('family_name', models.CharField(db_column='家庭名', max_length=20)),
            ],
            options={
                'db_table': '家庭表',
            },
        ),
    ]
