# Generated by Django 2.2.2 on 2019-11-16 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userManage', '0001_initial'),
        ('familyManage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMembers',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('family_id', models.OneToOneField(db_column='家庭ID', on_delete=django.db.models.deletion.CASCADE, to='familyManage.Family')),
                ('members3', models.ForeignKey(blank=True, db_column='成员3', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members3', to='userManage.User')),
                ('members4', models.ForeignKey(blank=True, db_column='成员4', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members4', to='userManage.User')),
                ('members5', models.ForeignKey(blank=True, db_column='成员5', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members5', to='userManage.User')),
                ('members6', models.ForeignKey(blank=True, db_column='成员6', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members6', to='userManage.User')),
                ('members7', models.ForeignKey(blank=True, db_column='成员7', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members7', to='userManage.User')),
                ('members8', models.ForeignKey(blank=True, db_column='成员8', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members8', to='userManage.User')),
                ('parent1', models.ForeignKey(db_column='家长1', on_delete=django.db.models.deletion.CASCADE, to='userManage.User')),
                ('parent2', models.ForeignKey(blank=True, db_column='家长2', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members2', to='userManage.User')),
            ],
            options={
                'db_table': '家庭成员表',
            },
        ),
    ]
