# Generated by Django 2.2.2 on 2019-11-16 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('familyManage', '0002_familymembers'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='family_member',
            field=models.OneToOneField(db_column='家庭成员', default=1, on_delete=django.db.models.deletion.CASCADE, to='familyManage.FamilyMembers'),
            preserve_default=False,
        ),
    ]
