# Generated by Django 2.2.2 on 2019-11-17 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userManage', '0001_initial'),
        ('familyManage', '0003_family_family_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, db_column='申请时间')),
                ('applicant', models.ForeignKey(db_column='申请者', on_delete=django.db.models.deletion.CASCADE, related_name='applicant', to='userManage.User')),
                ('interviewer', models.ForeignKey(db_column='审核者', on_delete=django.db.models.deletion.CASCADE, related_name='interviewer', to='userManage.User')),
            ],
        ),
    ]
