# Generated by Django 2.2.2 on 2019-11-17 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familyManage', '0004_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familymembers',
            name='family_id',
        ),
    ]
